### ISSUE TITLE
java.io.FileNotFoundException in example app

### ISSUE THREAD

**Issue by Prathik-Jain** [fengqiangboy/flutter-nordic-dfu#2]
The test function has the `filePath` as in the `pubspec.yaml` and I also have the following directory structure

```
./
├── android/
│   ├── app/
│   ├── build.gradle
│   ├── gradle/
│   ├── gradle.properties
│   ├── gradlew*
│   ├── gradlew.bat
│   ├── local.properties
│   └── settings.gradle
├── assets/
│   └── sense_pir_10000_010.zip
├── build/
│   ├── app/
│   ├── app.dill
│   ├── app.dill.track.dill
│   ├── app.dill.track.dill.incremental.dill
│   ├── flutter_nordic_dfu/
│   ├── frontend_server.d
│   └── kotlin/
├── ios/
│   ├── Flutter/
│   ├── Podfile
│   ├── Runner/
│   ├── Runner.xcodeproj/
│   └── Runner.xcworkspace/
├── lib/
│   └── main.dart
├── pubspec.lock
├── pubspec.yaml
├── README.md
└── test/
    └── widget_test.dart
```

> pubspec.yaml
```
to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/sense_pir_10000_010.zip
```

> Test function
 ```dart
void test() async {
    var s = await FlutterNordicDfu.startDfu(
        'C6:9D:C8:B6:4F:24', 'assets/sense_pir_10000_010.zip',
        progressListener: ProgressListenerListener());
    print(s);
  }
```

> Error
```
Launching lib/main.dart on devicein debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
E/CheckPermission( 4908): _bluetooth code = 1
D/AndroidRuntime( 4908): Shutting down VM
E/DfuBaseService( 4908): An exception occurred while opening file
E/DfuBaseService( 4908): java.io.FileNotFoundException: assets/sense_pir_10000_010.zip (No such file or directory)
E/DfuBaseService( 4908): 	at java.io.FileInputStream.open0(Native Method)
E/DfuBaseService( 4908): 	at java.io.FileInputStream.open(FileInputStream.java:200)
E/DfuBaseService( 4908): 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
E/DfuBaseService( 4908): 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
E/DfuBaseService( 4908): 	at no.nordicsemi.android.dfu.DfuBaseService.openInputStream(DfuBaseService.java:1418)
E/DfuBaseService( 4908): 	at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1160)
E/DfuBaseService( 4908): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
E/DfuBaseService( 4908): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/DfuBaseService( 4908): 	at android.os.Looper.loop(Looper.java:197)
E/DfuBaseService( 4908): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/AndroidRuntime( 4908): FATAL EXCEPTION: main
E/AndroidRuntime( 4908): Process: com.timeyaa.flutternordicdfuexample, PID: 4908
E/AndroidRuntime( 4908): android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=dfu pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0xff888888 vis=PRIVATE)
```

**Comment by fengqiangboy** [comment]
Current, you should pass a absolute path to `FlutterNordicDfu.startDfu` like "/data/local/tmp/file.zip".

**Comment by Prathik-Jain** [comment]
@fengqiangboy Absolute path from the root of the app?
Should It be updated in the `pubspec.yaml` as well?
Example would be much appreciated :smile:

**Comment by fengqiangboy** [comment]
In early version, I use `assets/file.zip` to test, because at the time I use a tool to get Asset file in native code, but it would import third dependent, so I remove it now.

I will consider how to achieve better implementation that  can get flutter assets file path in native code.

**Comment by Prathik-Jain** [comment]
Oh, which plugin did you use earlier? can you also give me an estimate on how long will you take to implement your version of the same?

I'll keep this issue open until then.

**Comment by fengqiangboy** [comment]
Use [com.blankj:utilcode](https://github.com/Blankj/AndroidUtilCode),

the code look like:

```Kotlin
// assets file from flutter
filePath = "assets/file.zip"

filePath = registrar.lookupKeyForAsset(filePath)

val tempFileName = PathUtils.getExternalAppCachePath() + UUID.randomUUID().toString()

// copy asset file to temp path
ResourceUtils.copyFileFromAssets(filePath, tempFileName)

// now, the path is an absolute path, and can pass it to nordic dfu libarary
filePath = tempFileName
```

**Comment by fengqiangboy** [comment]
Current, it can support asset file in flutter, you can try it in version `2.0.0`

```
await FlutterNordicDfu.startDfu(
            'EB:75:AD:E3:CA:CF', 'assets/file.zip',
            progressListener: ProgressListenerListener(),

/// asset file should add this parameter
            fileInAsset: true,
         );
```
